name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Getting the code
      uses: actions/checkout@v3

    - name: Install Node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Pull and start API Docker image
      run: |
        docker pull thiagoluppi/apiqax:v1
        docker run -d -p 3333:3333 thiagoluppi/apiqax:v1

    - name: Pull and start Web Docker image
      run: |
        docker pull thiagoluppi/webqax:v1
        docker run -d -p 3000:3000 thiagoluppi/webqax:v1

    - name: Setup and start ngrok for API
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
        ngrok authtoken $NGROK_AUTH_TOKEN
        ngrok http 3333 &

    - name: Wait for ngrok to initialize
      run: sleep 10  # give some time for ngrok to start

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run E2E tests
      run: npm run regression

    - name: Publish HTML Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
















# name: Playwright Tests
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]
#   workflow_dispatch:
# jobs:
#   e2e-tests:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - name: Getting the code
#       uses: actions/checkout@v3

#     - name: Install Node 18
#       uses: actions/setup-node@v3
#       with:
#         node-version: 18

#     - name: Install dependencies
#       run: npm install

#     - name: Install Playwright Browsers
#       run: npx playwright install --with-deps

#     - name: Run E2E tests
#       run: npm run regression

#     - name: Publish HTML Report
#       uses: actions/upload-artifact@v3
#       if: always()
#       with:
#         name: playwright-report
#         path: playwright-report/
#         retention-days: 30